Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: "wsi"

Resources:
  KinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub ${EnvironmentName}-kinesis
      RetentionPeriodHours: 24
      ShardCount: 1
      StreamModeDetails:
        StreamMode: PROVISIONED
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-kinesis

Outputs:
  KinesisDataStream:
    Description: "Kinesis Data Stream"
    Value: !Ref KinesisDataStream
    Export:
      Name:
        "Fn::Sub": "${AWS::StackName}-KDS"
